name: NotzScoreboardV3
version: 0.4
main: dev.kaato.Main

commands:
  nscoreboard:
    description: notzscoreboard admin command
    usage: /nsb
    aliases:
      - notzscoreboard
      - notzsb
      - nsb
permissions:
  notzscoreboard.admin:
    description: Admin perm
    default: false